#configMap & secrets as env's 
kind: Deployment
apiversion: aaps/v1
metadata:
  name: mywebdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
template:
  metadata:
    name: mypo
    labels:
      env: dev
  spec:
    containers:
      - name: mycont
        image: suribau/web:v1.12
        env:
        - name: URI
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: MONGODB_URI
        - name: USER
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
               
